/**
*		DB INSTALL 프로세스
*
*		01. 테이블 스페이스 생성(TS_LUNA_OPS_DPL_DAT01, TS_LUNA_OPS_DPL_IDX01)
*		02. LUNAOPSDPLDB 스키마 생성
*		03. LUNAOPSDPLDB 스키마에 권한 부여
*		04. 테이블 및 칼럼 메타정보 테이블 및 테이블 생성 SQL 저장 테이블 생성
*		05. 메타정보 테이블에 메타정보 데이터 INSERT
*
*		작성자 : (주)오픈소프트랩 정형택
*		작성일 : 2018.10.29
*/


/* TS_LUNA_OPS_DPL_DAT01 데이터 저장용 테이블 스페이스 생성 */
CREATE TABLESPACE TS_LUNA_OPS_DPL_DAT01 DATAFILE
'C:\ORACLE\ORADATA\SDF\TS_LUNA_OPS_DPL_DAT01.DBF' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K;

/* TS_LUNA_OPS_DPL_IDX01 인덱스 저장용 테이블 스페이스 생성 */
CREATE TABLESPACE TS_LUNA_OPS_DPL_IDX01 DATAFILE
'C:\ORACLE\ORADATA\SDF\TS_LUNA_OPS_DPL_IDX01.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K;


/* LUNAOPSDPLDB 스키마 생성 및 권한 부여 */
CREATE USER LUNAOPSDPLDB IDENTIFIED BY LUNAOPSDPLDB;
GRANT CONNECT,RESOURCE TO LUNAOPSDPLDB IDENTIFIED BY LUNAOPSDPLDB;
GRANT CREATE VIEW TO LUNAOPSDPLDB;
ALTER USER LUNAOPSDPLDB DEFAULT TABLESPACE TS_LUNA_OPS_DPL_DAT01;
ALTER USER LUNAOPSDPLDB TEMPORARY TABLESPACE TEMP;

GRANT CREATE DATABASE LINK TO LUNAOPSDPLDB;
GRANT CREATE JOB TO LUNAOPSDPLDB;
GRANT CREATE VIEW TO LUNAOPSDPLDB;
GRANT CREATE MATERIALIZED VIEW TO LUNAOPSDPLDB;
GRANT CREATE PROCEDURE TO LUNAOPSDPLDB;
GRANT CREATE SEQUENCE TO LUNAOPSDPLDB;
GRANT CREATE SYNONYM TO LUNAOPSDPLDB;
GRANT CREATE TABLE TO LUNAOPSDPLDB;
GRANT CREATE TRIGGER TO LUNAOPSDPLDB;

/* ORACLE 12C 에서는 아래 테이블 스페이스 사용량 언리미티드로 지정 해 줘야함. */
alter user LUNAOPSDPLDB default tablespace TS_LUNA_OPS_DPL_DAT01 quota unlimited on TS_LUNA_OPS_DPL_DAT01;
alter user LUNAOPSDPLDB default tablespace TS_LUNA_OPS_DPL_IDX01 quota unlimited on TS_LUNA_OPS_DPL_IDX01;

/* 시퀀스 생성 */
CREATE SEQUENCE LUNAOPSDPLDB.LIC_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    MINVALUE 1
    NOCACHE
    ORDER;

/* 테이블 및 칼럼 메타정보 테이블 생성 */
CREATE TABLE LUNAOPSDPLDB.TB_META_INFO (
  TABLE_NAME       VARCHAR2(200 BYTE)     NOT NULL,
  COLUMN_NAME      VARCHAR2(200 BYTE)     NOT NULL,
  TABLE_COMMENT     VARCHAR2(200 BYTE)         NULL,
  COLUMN_COMMENT    VARCHAR2(200 BYTE)         NULL,
  COL_SEQ          NUMBER(3)                  NULL,
  PK               VARCHAR2(2 BYTE)           NULL,
  FK               VARCHAR2(2 BYTE)           NULL,
  NOT_NULL         VARCHAR2(1 BYTE)           NULL,
  DATA_TYPE        VARCHAR2(200 BYTE)         NULL,
  DATA_LENGTH      VARCHAR2(200 BYTE)         NULL,
  DEFAULT_VALUE	   VARCHAR2(200 BYTE)	      NULL,
  REMARK	   VARCHAR2(500 BYTE)         NULL,
  CONSTRAINT PK_TB_META_INFO PRIMARY KEY ( TABLE_NAME, COLUMN_NAME )
  USING INDEX TABLESPACE TS_LUNA_OPS_DPL_IDX01
)
TABLESPACE TS_LUNA_OPS_DPL_DAT01;

COMMENT ON TABLE LUNAOPSDPLDB.TB_META_INFO IS '테이블 및 칼럼 메타정보 테이블';

COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.TABLE_NAME IS '테이블명';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.COLUMN_NAME IS '칼럼명';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.TABLE_COMMENT IS '테이블 코멘트';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.COLUMN_COMMENT IS '칼럼 코멘트';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.COL_SEQ IS '컬럼 생성 순서';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.PK IS '주키 여부';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.FK IS '보조키 여부여부';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.NOT_NULL IS 'NOT NULL 여부';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.DATA_TYPE IS '데이터 자료형';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.DATA_LENGTH IS '데이터 길이';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.DEFAULT_VALUE IS '디폴트값';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_META_INFO.REMARK IS '비고';


/* 테이블 생성 SQL 저장 테이블 생성 */
CREATE TABLE LUNAOPSDPLDB.TB_CREATE_SQL_INFO
(
  TABLE_NAME VARCHAR2(200) NOT NULL,
  DDL_GB VARCHAR2(1),
  CREATE_SQL CLOB,
  CONSTRAINT PK_TB_CREATE_SQL_INFO PRIMARY KEY(TABLE_NAME, DDL_GB)
  USING INDEX TABLESPACE TS_LUNA_OPS_DPL_IDX01
)
TABLESPACE TS_LUNA_OPS_DPL_DAT01;

COMMENT ON TABLE LUNAOPSDPLDB.TB_CREATE_SQL_INFO IS '테이블 생성 SQL 저장 테이블';

COMMENT ON COLUMN LUNAOPSDPLDB.TB_CREATE_SQL_INFO.TABLE_NAME IS '테이블명';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_CREATE_SQL_INFO.DDL_GB IS '생성된 스크립트 구분(C: 테이블생성, I: 마이그레이션)';
COMMENT ON COLUMN LUNAOPSDPLDB.TB_CREATE_SQL_INFO.CREATE_SQL IS '생성 스크립트';
