


/* 공통코드 마스터 테이블 생성 SQL */
CREATE TABLE CMM1000
(
MST_CD VARCHAR2(8) NOT NULL  , 
UPPER_MST_CD VARCHAR2(8) , 
MST_CD_NM VARCHAR2(50) NOT NULL  , 
MST_CD_ENG_NM VARCHAR2(50) , 
MST_CD_DESC VARCHAR2(200) , 
ABORT_DT CHAR(8) , 
LVL NUMBER , 
ORD NUMBER , 
USE_YN CHAR(1) , 
STM_USE_YN CHAR(1) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_CMM1000 PRIMARY KEY(MST_CD )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 공통코드 디테일 테이블 생성 SQL */
CREATE TABLE CMM1001
(
MST_CD VARCHAR2(8) NOT NULL  , 
SUB_CD VARCHAR2(3) NOT NULL  , 
SUB_CD_NM VARCHAR2(50) NOT NULL  , 
ORD NUMBER , 
USE_YN CHAR(1) , 
SUB_CD_REF1 VARCHAR2(50) , 
SUB_CD_REF2 VARCHAR2(50) , 
SUB_CD_REF3 VARCHAR2(50) , 
SUB_CD_REF4 VARCHAR2(50) , 
SUB_CD_REF5 VARCHAR2(50) , 
SUB_CD_DESC VARCHAR2(200) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_CMM1001 PRIMARY KEY(MST_CD , SUB_CD )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 배포계획 정보 테이블 생성 SQL */
CREATE TABLE DPL1000
(
CI_ID VARCHAR2(20) NOT NULL  , 
TICKET_ID VARCHAR2(20) NOT NULL  , 
DPL_ID VARCHAR2(16) NOT NULL  , 
DPL_NM VARCHAR2(200) , 
DPL_VER VARCHAR2(100) , 
DPL_DT  DATE , 
DPL_USR_ID VARCHAR2(20) , 
DPL_DESC VARCHAR2(1000) , 
DPL_STS_CD VARCHAR2(2) , 
DPL_TYPE_CD VARCHAR2(2) , 
DPL_AUTO_AFTER_CD VARCHAR2(2) , 
DPL_AUTO_DTM DATE , 
DPL_RESTORE_CD VARCHAR2(2) , 
DPL_DEL_CD VARCHAR2(2) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_DPL1000 PRIMARY KEY(CI_ID , TICKET_ID , DPL_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 배포 JOB 목록 테이블 생성 SQL */
CREATE TABLE DPL1100
(
CI_ID VARCHAR2(20) NOT NULL  , 
TICKET_ID VARCHAR2(20) NOT NULL  , 
DPL_ID VARCHAR2(16) NOT NULL  , 
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
JOB_START_ORD NUMBER , 
USE_CD VARCHAR2(2) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_DPL1100 PRIMARY KEY(CI_ID , TICKET_ID , DPL_ID , JEN_ID , JOB_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 배포 JOB 파라미터 정보 테이블 생성 SQL */
CREATE TABLE DPL1101
(
CI_ID VARCHAR2(20) NOT NULL  , 
TICKET_ID VARCHAR2(20) NOT NULL  , 
DPL_ID VARCHAR2(16) NOT NULL  , 
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
JOB_PARAM_KEY VARCHAR2(50) NOT NULL  , 
JOB_PARAM_VAL VARCHAR2(50) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_DPL1101 PRIMARY KEY(CI_ID , TICKET_ID , DPL_ID , JEN_ID , JOB_ID , JOB_PARAM_KEY )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 배포 계획 실행 정보 테이블 생성 SQL */
CREATE TABLE DPL1102
(
CI_ID VARCHAR2(20) NOT NULL  , 
TICKET_ID VARCHAR2(20) NOT NULL  , 
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
DPL_ID VARCHAR2(16) NOT NULL  , 
BLD_NUM NUMBER NOT NULL  , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_DPL1102 PRIMARY KEY(CI_ID , TICKET_ID , JEN_ID , JOB_ID , DPL_ID , BLD_NUM )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* JENKINS 정보 테이블 생성 SQL */
CREATE TABLE JEN1000
(
JEN_ID VARCHAR2(16) NOT NULL  , 
JEN_NM VARCHAR2(500) NOT NULL  , 
JEN_USR_ID VARCHAR2(20) , 
JEN_USR_TOK VARCHAR2(1000) , 
JEN_URL VARCHAR2(500) , 
JEN_DESC VARCHAR2(2000) , 
USE_CD VARCHAR2(2) , 
DEL_CD VARCHAR2(2) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_JEN1000 PRIMARY KEY(JEN_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* JOB 정보 테이블 생성 SQL */
CREATE TABLE JEN1100
(
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
JOB_RESTORE_ID VARCHAR2(500) , 
JOB_TOK VARCHAR2(200) , 
JOB_DESC VARCHAR2(2000) , 
JOB_TYPE_CD VARCHAR2(2) , 
JOB_URL VARCHAR2(500) , 
JOB_TRIGGER_CD VARCHAR2(2) , 
USE_CD VARCHAR2(2) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_JEN1100 PRIMARY KEY(JEN_ID , JOB_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* JOB 연결 정보 테이블 생성 SQL */
CREATE TABLE JEN1101
(
CI_ID VARCHAR2(20) NOT NULL  , 
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_JEN1101 PRIMARY KEY(CI_ID , JEN_ID , JOB_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* JOB 기본 파라미터 정보 테이블 생성 SQL */
CREATE TABLE JEN1102
(
CI_ID VARCHAR2(20) NOT NULL  , 
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
JOB_PARAM_KEY VARCHAR2(50) NOT NULL  , 
JOB_PARAM_VAL VARCHAR2(50) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_JEN1102 PRIMARY KEY(CI_ID , JEN_ID , JOB_ID , JOB_PARAM_KEY )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* JOB 빌드 이력 테이블 생성 SQL */
CREATE TABLE JEN1200
(
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
BLD_NUM NUMBER NOT NULL  , 
BLD_CLASS VARCHAR2(500) , 
BLD_RESULT VARCHAR2(20) , 
BLD_RESULT_CD VARCHAR2(2) , 
BLD_ETM_DURATION_TM NUMBER , 
BLD_DURATION_TM NUMBER , 
BLD_START_DTM DATE , 
BLD_CONSOLE_LOG CLOB DEFAULT empty_clob()  , 
BLD_CAUSES VARCHAR2(200) , 
BLD_ACTION_LOG VARCHAR2(4000) , 
CI_ID VARCHAR2(20) , 
TICKET_ID VARCHAR2(20) , 
DPL_ID VARCHAR2(16) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_JEN1200 PRIMARY KEY(JEN_ID , JOB_ID , BLD_NUM )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;



/* JOB 빌드 변경 정보 테이블 생성 SQL */
CREATE TABLE JEN1201
(
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
BLD_NUM NUMBER NOT NULL  , 
CHG_REVISION VARCHAR2(50) NOT NULL  , 
CHG_TIMESTAMP VARCHAR2(50) , 
CHG_DATE VARCHAR2(50) , 
CHG_MSG VARCHAR2(4000) , 
CHG_USER VARCHAR2(50) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_JEN1201 PRIMARY KEY(JEN_ID , JOB_ID , BLD_NUM , CHG_REVISION )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* JOB 빌드 변경 파일 정보 테이블 생성 SQL */
CREATE TABLE JEN1202
(
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
BLD_NUM NUMBER NOT NULL  , 
CHG_REVISION VARCHAR2(50) NOT NULL  , 
FILE_PATH VARCHAR2(256) NOT NULL  , 
EDIT_TYPE_CD VARCHAR2(10) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_JEN1202 PRIMARY KEY(JEN_ID , JOB_ID , BLD_NUM , CHG_REVISION , FILE_PATH )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* JOB 빌드 파라미터 정보 테이블 생성 SQL */
CREATE TABLE JEN1203
(
JEN_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
BLD_NUM NUMBER NOT NULL  , 
JOB_PARAM_KEY VARCHAR2(50) NOT NULL  , 
JOB_PARAM_VAL VARCHAR2(50) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_JEN1203 PRIMARY KEY(JEN_ID , JOB_ID , BLD_NUM , JOB_PARAM_KEY )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* LOCK 정보 테이블 생성 SQL */
CREATE TABLE LCK1000
(
REP_ID VARCHAR2(16) NOT NULL  , 
LOCK_ID VARCHAR2(300) NOT NULL  , 
LOCK_STATE_CD VARCHAR2(2) NOT NULL  , 
LOCK_PATH VARCHAR2(1000) , 
LOCK_USR_ID VARCHAR2(50) , 
LOCK_COMMENT VARCHAR2(2000) , 
LOCK_FORCE VARCHAR2(20) , 
LOCK_TARGET_RV VARCHAR2(50) , 
TICKET_ID VARCHAR2(100) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_LCK1000 PRIMARY KEY(REP_ID , LOCK_ID , LOCK_STATE_CD )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 시스템 사용이력 정보 테이블 생성 SQL */
CREATE TABLE LOG1000
(
LOG_SEQ NUMBER(23) NOT NULL  , 
LOG_TIME DATE , 
LOG_URL VARCHAR2(500) , 
LOG_USR_ID VARCHAR2(20) , 
LOG_IP VARCHAR2(39) , 
LOG_TYPE VARCHAR2(10) , 
LOG_AJAX_CD VARCHAR2(2) , 
LOG_PARAM_DATA1 VARCHAR2(4000) , 
LOG_PARAM_DATA2 VARCHAR2(4000) , 
LOG_PARAM_DATA3 VARCHAR2(4000) , 

CONSTRAINT PK_LOG1000 PRIMARY KEY(LOG_SEQ )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 소스저장소 정보 테이블 생성 SQL */
CREATE TABLE REP1000
(
REP_ID VARCHAR2(16) NOT NULL  , 
REP_NM VARCHAR2(500) NOT NULL  , 
REP_TYPE_CD VARCHAR2(2) , 
REP_TXT VARCHAR2(1000) , 
REP_UUID VARCHAR2(150) , 
REP_DPL_UUID VARCHAR2(150) , 
SVN_REP_URL VARCHAR2(500) , 
SVN_USR_ID VARCHAR2(30) , 
SVN_USR_PW VARCHAR2(256) , 
SVN_BRC_PATH VARCHAR2(500) , 
GIT_USR_AUTH_TYPE_CD VARCHAR2(2) , 
GIT_REP_URL VARCHAR2(256) , 
GIT_USR_ID VARCHAR2(30) , 
GIT_USR_PW VARCHAR2(256) , 
GIT_USR_TK VARCHAR2(256) , 
DPL_REP_URL VARCHAR2(500) , 
DPL_USR_ID VARCHAR2(30) , 
DPL_USR_PW VARCHAR2(256) , 
DPL_USE_CD VARCHAR2(2) , 
USE_CD VARCHAR2(2) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_REP1000 PRIMARY KEY(REP_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 소스저장소 연결 정보 테이블 생성 SQL */
CREATE TABLE REP1001
(
CI_ID VARCHAR2(20) NOT NULL  , 
REP_ID VARCHAR2(16) NOT NULL  , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_REP1001 PRIMARY KEY(CI_ID , REP_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 소스저장소 리비전 정보 테이블 생성 SQL */
CREATE TABLE REP1100
(
TICKET_ID VARCHAR2(100) NOT NULL  , 
REP_ID VARCHAR2(16) NOT NULL  , 
REP_RV NUMBER NOT NULL  , 
REP_RV_TYPE_CD VARCHAR2(2) NOT NULL  , 
REP_COMMENT VARCHAR2(1000) , 
REP_CMT_DATE DATE , 
REP_CMT_AUTHOR VARCHAR2(50) , 
REP_CHG_FILE_CNT NUMBER , 
GIT_CMT_SHA VARCHAR2(50) , 
GIT_BRC_NM VARCHAR2(50) , 

CONSTRAINT PK_REP1100 PRIMARY KEY(TICKET_ID , REP_ID , REP_RV , REP_RV_TYPE_CD )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 소스저장소 리비전 파일 변경정보 테이블 생성 SQL */
CREATE TABLE REP1101
(
TICKET_ID VARCHAR2(100) NOT NULL  , 
REP_ID VARCHAR2(16) NOT NULL  , 
REP_RV NUMBER NOT NULL  , 
REP_CHG_ID VARCHAR2(16) NOT NULL  , 
REP_CHG_TYPE_CD VARCHAR2(2) , 
REP_CHG_FILE_PATH VARCHAR2(500) , 
REP_CHG_FILE_NM VARCHAR2(150) , 
REP_CHG_FILE_KIND VARCHAR2(20) , 
REP_TARGET_RV VARCHAR2(50) , 
REP_TARGET_FILE_PATH VARCHAR2(500) , 
COMMIT_EMP_ID VARCHAR2(50) , 

CONSTRAINT PK_REP1101 PRIMARY KEY(TICKET_ID , REP_ID , REP_RV , REP_CHG_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 빌드저장소 파일 변경정보 테이블 생성 SQL */
CREATE TABLE REP1102
(
TICKET_ID VARCHAR2(100) NOT NULL  , 
CI_ID VARCHAR2(20) NOT NULL  , 
REP_ID VARCHAR2(16) NOT NULL  , 
REP_RV NUMBER NOT NULL  , 
REP_CHG_ID VARCHAR2(16) NOT NULL  , 
JOB_ID VARCHAR2(256) NOT NULL  , 
BLD_NUM NUMBER NOT NULL  , 
REP_CHG_TYPE_CD VARCHAR2(2) , 
REP_CHG_FILE_PATH VARCHAR2(500) , 
REP_CHG_FILE_NM VARCHAR2(150) , 
REP_CHG_FILE_KIND VARCHAR2(20) , 
REP_CHG_SEL_CD VARCHAR2(20) , 
COMMIT_EMP_ID VARCHAR2(50) , 

CONSTRAINT PK_REP1102 PRIMARY KEY(TICKET_ID , CI_ID , REP_ID , REP_RV , REP_CHG_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 사용자 정보 테이블 생성 SQL */
CREATE TABLE USR1000
(
EMP_ID VARCHAR2(100) NOT NULL  , 
EMP_PASSWD VARCHAR2(256) , 
EMP_NAME VARCHAR2(200) NOT NULL  , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_USR1000 PRIMARY KEY(EMP_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 웹훅 정보 테이블 생성 SQL */
CREATE TABLE WHK1000
(
WEBHOOK_ID VARCHAR2(16) NOT NULL  , 
WEBHOOK_NM VARCHAR2(100) , 
WEBHOOK_TYPE_CD VARCHAR2(2) , 
WEBHOOK_CHG_TYPE_CD VARCHAR2(2) , 
WEBHOOK_TARGET_URL VARCHAR2(500) , 
CONTENT_TYPE_CD VARCHAR2(2) , 
USE_CD VARCHAR2(2) , 
REG_DTM DATE , 
REG_USR_ID VARCHAR2(20) , 
REG_USR_IP VARCHAR2(39) , 
MODIFY_DTM DATE , 
MODIFY_USR_ID VARCHAR2(20) , 
MODIFY_USR_IP VARCHAR2(39) , 

CONSTRAINT PK_WHK1000 PRIMARY KEY(WEBHOOK_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;


/* 웹훅 로그 테이블 생성 SQL */
CREATE TABLE WHK1001
(
WEBHOOK_ID VARCHAR2(16) NOT NULL  , 
WEBHOOK_LOG_ID VARCHAR2(16) NOT NULL  , 
WEBHOOK_RESULT NUMBER , 
WEBHOOK_DATE DATE , 
WEBHOOK_DATA VARCHAR2(4000) , 
WEBHOOK_LOG VARCHAR2(4000) , 
WEBHOOK_RESULT_DATA VARCHAR2(4000) , 
WEBHOOK_USR_ID VARCHAR2(50) , 
WEBHOOK_TARGET_URL VARCHAR2(500) , 

CONSTRAINT PK_WHK1001 PRIMARY KEY(WEBHOOK_ID , WEBHOOK_LOG_ID )
USING INDEX TABLESPACE TS_LUNA_PIPE_IDX
)
TABLESPACE TS_LUNA_PIPE_DAT;

