CREATE INDEX IDX_REP1102 
ON REP1102 
(
	"TICKET_ID","REP_ID","CI_ID","JOB_ID","BLD_NUM"
)
;
CREATE INDEX IDX_REP1101 
ON REP1101 
(
	"REP_ID","REP_RV","REP_CHG_FILE_PATH","REP_CHG_FILE_NM"
)
;
CREATE INDEX IDX_EXT_REP1102 
ON REP1102 
(
	"CI_ID","TICKET_ID"
)

CREATE INDEX IDX_SEL_REP1102 
ON REP1102 
(
	"TICKET_ID","CI_ID","REP_ID","REP_CHG_SEL_CD"
)
